#! /usr/bin/Rscript
# usage:
# ./make_slides module0_induction
# ./make_slides module1_basics
# etc.

library(rmarkdown)

module <- commandArgs(trailingOnly = TRUE)
source <- paste(module, ".Rmd", sep = "")

if (file.exists(source)){
    render(source, envir = new.env(), clean = FALSE)
    file.rename(paste(module, ".html", sep = ""), paste(module, "_onepage", ".html", sep = ""))
    system(paste("pandoc -s --webtex -t slidy ", paste(module, ".knit.md", sep = ""), " -o ", paste(module, ".html", sep = ""), " --embed-resources --standalone"))
} else {
    cat("Error: ", source, "does not exist.\n")
}
